volumes:
  passport_pals:
    external: true
  jwtdown-db-data:
    external: true
services:
  fastapi:
    build:
      context: ./passport_pals
      dockerfile: Dockerfile.dev
    environment:
      SIGNING_KEY: D4KQq0RcL96pGFwqXfAom3ZFU3X3w6vw0R5HGfv3V6U
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      DATABASE_URL: mongodb://passportpals:passportpals@mongo
      DATABASE_NAME: passport_pals
    ports:
      - 8000:8000
    volumes:
      - ./passport_pals:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_PASSPORT_PALS_API_HOST: http://localhost:8000

  mongo:
    image: mongo:4
    volumes:
      - passport_pals:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: passportpals
      MONGO_INITDB_ROOT_PASSWORD: passportpals
    ports:
      - 27017:27017
